const fs = require(" fs\); fs.writeFileSync(\C:/Users/rajat/PrepKit/package.json\, JSON.stringify({
 name: \prepkit\,
 version: \1.0.0\,
 private: true,
 scripts: {
 dev: \next dev\,
 build: \next build\,
 start: \next start\,
 lint: \next lint\,
 test: \jest\,
 \test:watch\: \jest --watch\,
 \test:coverage\: \jest --coverage\
 },
 dependencies: {
 next: \14.2.0\,
 react: \18.3.0\,
 \react-dom\: \18.3.0\,
 mongodb: \6.5.0\,
 zod: \3.23.0\,
 bcryptjs: \2.4.3\,
 jsonwebtoken: \9.0.2\,
 axios: \1.7.0\,
 cheerio: \1.0.0\,
 \robots-parser\: \3.0.1\,
 \node-cron\: \3.0.3\,
 \@radix-ui/react-tabs\: \1.0.4\,
 \@radix-ui/react-dialog\: \1.0.5\,
 \@radix-ui/react-dropdown-menu\: \2.0.6\,
 \@radix-ui/react-progress\: \1.0.3\,
 \@radix-ui/react-toast\: \1.1.5\,
 \@radix-ui/react-label\: \2.0.2\,
 \@radix-ui/react-select\: \2.0.0\,
 \@radix-ui/react-slider\: \1.1.2\,
 \lucide-react\: \0.378.0\,
 clsx: \2.1.0\,
 \tailwind-merge\: \2.3.0\,
 \date-fns\: \3.6.0\
 },
 devDependencies: {
 typescript: \^5.4.0\,
 \@types/react\: \^18.3.0\,
 \@types/node\: \^20.12.0\,
 \@types/bcryptjs\: \^2.4.6\,
 \@types/jsonwebtoken\: \^9.0.6\,
 \@types/cheerio\: \^0.22.35\,
 \@types/node-cron\: \^3.0.11\,
 jest: \^29.7.0\,
 \@types/jest\: \^29.5.12\,
 \ts-jest\: \^29.1.2\,
 supertest: \^7.0.0\,
 \@types/supertest\: \^6.0.2\,
 eslint: \^8.57.0\,
 \@typescript-eslint/parser\: \^7.0.0\,
 \@typescript-eslint/eslint-plugin\: \^7.0.0\,
 tailwindcss: \^3.4.0\,
 postcss: \^8.4.38\,
 autoprefixer: \^10.4.19\
 }
}, null, 2)); console.log(\package.json written\);